name: bimed
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-22.0.dev <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  intl: ^0.17.0   # this help me format Date
  http: ^0.13.4
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.1.5
  flutter_icons: ^1.1.0
  intl_phone_field: ^3.1.0
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  flutter_easyloading: ^3.0.3
  device_info: ^2.0.3 # device info

  scrolling_page_indicator: ^0.1.3 # scrolling
  
  dio: ^4.0.4 # dio
  pretty_dio_logger: ^1.1.1
  optimized_cached_image: ^3.0.0

  freezed_annotation: ^2.0.1

  flutter_countdown_timer: ^4.1.0 # count down timer
  phone_number: ^0.12.0+2 # for parsing

  image_picker: ^0.8.4+11 # imagePicker

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1 # bloc
  bloc_concurrency: ^0.2.0

  flutter_hooks: ^0.18.3 # hooks
  retrofit: ^3.0.1+1
  flutter_cupertino_localizations: ^1.0.1
  flutter_staggered_grid_view: ^0.6.1

  cupertino_will_pop_scope: ^1.2.0

  sqflite: ^2.0.2+1 # SQLite
  url_launcher: ^6.1.3

  page_slider: ^0.0.2 # Page Slider
  badges: ^2.0.3 # Badge
  group_button: ^5.0.1 # group button (check box)

flutter_icons:
  image_path: "asset/splash.png" 
  android: true
  ios: true

flutter_native_splash:
  color: "#054EDB"
  image: asset/splash.png
  android: true
  ios: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2 # freezed  
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  lint: ^1.8.2

  flutter_launcher_icons: ^0.9.2 # app icon
  retrofit_generator: ^4.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: asset/fonts/Inter-Black.ttf
          weight: 900
        - asset: asset/fonts/Inter-Bold.ttf
          weight: 700
        - asset: asset/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Inter-ExtraLight.ttf   
          weight: 200
        - asset: asset/fonts/Inter-Light.ttf
          weight: 300
        - asset: asset/fonts/Inter-Medium.ttf
          weight: 500
        - asset: asset/fonts/Inter-Regular.ttf
          weight: 400
        - asset: asset/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Inter-Thin.ttf
          weight: 100    
    - family: BimedIcons
      fonts: 
        - asset: asset/icons/BimedIcons.ttf 
        - asset: asset/icons/success.svg       
        - asset: asset/icons/about_company.svg
        - asset: asset/icons/filials.svg
        - asset: asset/icons/heart.svg
        - asset: asset/icons/help.svg
        - asset: asset/icons/news.svg
        - asset: asset/icons/phone.svg
        - asset: asset/icons/time.svg
        - asset: asset/icons/user.svg
        - asset: asset/icons/search.svg
        - asset: asset/icons/notification.svg
        - asset: asset/icons/logout.svg
        - asset: asset/icons/trash.svg
        - asset: asset/icons/whatsapp.svg
        - asset: asset/user.png
        - asset: asset/medicine.png
        - asset: asset/free_delivary.png
        - asset: asset/how_to_order.png
        - asset: asset/map_of_aptec.png
        - asset: asset/icons/arrow_down.svg
        - asset: asset/icons/block_one.svg
        - asset: asset/icons/bloc_grid.svg

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
